config/routes.rb
Rails.application.routes.draw do
  # root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "pokemons#index"
  resources :trainers, only: [:index, :show, :new, :create]
  resources :pokemons do
    resources :pokeballs, only: [:create]
  end
  get 'search', to: 'pokemons#search', as: 'search_pokemons'
  get 'random', to: 'pokemons#random', as: 'random_pokemon'
  resources :pokeballs, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pokeball.rb
class Pokeball < ApplicationRecord
  belongs_to :pokemon
  belongs_to :trainer

  validates :location, presence: true
  validates :caught_on, presence: true
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  has_many :pokeballs
  has_many :trainers, through: :pokeballs
  has_one_attached :photo

  validates :name, presence: true
  validates :element_type, presence: true
end

app/models/trainer.rb
class Trainer < ApplicationRecord
  has_many :pokeballs
  has_many :pokemons, through: :pokeballs
  has_one_attached :photo

  validates :name, presence: true
  validates :age, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/pokeballs_controller.rb
class PokeballsController < ApplicationController
  def create
    @pokemon = Pokemon.find(params[:pokemon_id])
    @trainer = Trainer.find(pokeball_params[:trainer_id])
    @pokeball = Pokeball.new(pokeball_params)
    @pokeball.pokemon = @pokemon
    @pokeball.trainer = @trainer
    chance = [1, 2].sample
    should_save = chance == 1
    if should_save == false
      redirect_to trainer_path(@trainer),  notice: " You're just miss it! It got away" and return
    end
    if  @pokeball.save
        redirect_to trainer_path(@trainer), notice: "Congratulations! Pokemon catched!"
    else
      render "pokemons/show", notice: "error"
    end
  end


    def destroy
      @pokeball = Pokeball.find(params[:id])
      @pokeball.destroy
      redirect_to trainer_path(@pokeball.trainer), status: :see_other
    end


  private
  def pokeball_params
    params.require(:pokeball).permit(:location, :caught_on, :trainer_id)
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  def index
    if params[:search].present?
      @pokemons =  Pokemon.where("name ILIKE ?", "%#{params[:search]}%")
    else
      @pokemons = Pokemon.all
    end
  end

  def show
    @pokemon = Pokemon.find(params[:id])
  end

  def random
    pokemon_random = Pokemon.order("RANDOM()").take
    redirect_to pokemon_path(pokemon_random)
  end


  def search
    search_query = params[:search][:query]
    if search_query.present?
      @pokemons =  Pokemon.where("name ILIKE ?", "%#{search_query}%")
    else
      @pokemon = Pokemon.all
    end
    redirect_to pokemons_path(search: search_query)
  end

  private
  def search_params
    params.require(:search).permit(:query)
  end

end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  def index
    @trainers = Trainer.all
  end

  def new
    @trainer = Trainer.new
  end

  def create
    @trainer = Trainer.new(trainer_params)
    if @trainer.save
      redirect_to trainer_path(@trainer)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @trainer = Trainer.find(params[:id])
    @pokeballs = @trainer.pokeballs
  end

  private

    def trainer_params
      params.require(:trainer).permit(:name, :age, :photo)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPokemon</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Pixelify+Sans:wght@400..700&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
    <%= yield %>
    <%= render "shared/flashes" %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pokemons/index.html.erb
<div class="pokedex mt-3">Pokedex</div>
  <div class="trainers-link"><%= link_to "Trainers", trainers_path, class:" custom-color fs-2" %></div>
  <div class="random-link mt-1 mb-2"><%= link_to"Random Pokemon",random_pokemon_path, class:"custom-color fs-3" %></div>

  <div class="search my-3">
    <%= simple_form_for :search, url: search_pokemons_path, method: :get do |f| %>
      <div class="search-form-control form-group rounded-2">
        <%= f.input :query, label: false, required: true, input_html: { class: "form-control" } %>
        <button name="button" type="submit" class="btn btn-flat text-dark">
          Search
        </button>
      </div>
    <% end %>
  </div>

<div class="pokemons">
  <% @pokemons.each do |pokemon| %>
    <%= link_to pokemon_path(pokemon), class:"pokemon-card-link" do %>
    <div class="pokemon-card">
      <div class="img">
        <%= cl_image_tag pokemon.photo.key, height: 250, width: 200, crop: :fill %>
      </div>
      <div class="name fs-3">
        <%= pokemon.name %>
      </div>
      <div class="element fs-4 pb-3 text-dark">
      <%= pokemon.element_type %>
      </div>

    </div>
    <%end%>
  <% end %>
</div>

app/views/pokemons/show.html.erb
<%= link_to"Pokedex", root_path, class:" custom-color fs-3" %>
<h4 class="mt-2"><p>You hear a rustle in the tall grass...</p> <p>A wild Pokémon appears !</p></h4>

<div class="container">
  <div class="row">

     <div class="col">
      <div class="pokemon-card">
      <div class="img">
        <%= cl_image_tag @pokemon.photo.key, height: 300, width: 200, crop: :fill %>
      </div>
      <div class="name fs-3">
        <%= @pokemon.name %>
      </div>
      <div class="element fs-4 pb-3 text-dark">
      <%= @pokemon.element_type %>
      </div>
      </div>
      </div>

      <div class="col">
        <div class="catch-pokemon">
           <p>Do you dare to catch this pokemon ?</p>

          <div class="form text-dark">

          <%= simple_form_for [@pokemon, Pokeball.new] do |f| %>
          <%= f.label  "Who's trying their luck ?"%>
          <%= f.association :trainer, collection: Trainer.all, input_html: { class: "bg-secondary text-white" } %>

          <%= f.input :location, label: "Where are you?", input_html: { class: "bg-secondary text-white" } %>
          <%= f.input :caught_on, as: :date, label: "When?", input_html: { class: "bg-secondary text-white" } %>
          <%= f.submit "Catch !", class: "btn btn-primary fw-bold" %>
          <% end %>
          </div>
        </div>

      </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/trainers/index.html.erb
<%= link_to"<- Pokedex", root_path, class:"fs-3 custom-color" %>
<div class = "mt-3 fs-1 fw-bold">Let's get training </div>
  <div class="trainers">
    <% @trainers.each do |trainer| %>
      <%= link_to trainer_path(trainer), class: "trainer-card-link" do %>
      <div class="trainer-card my-3 py-3">
        <div class="img pb-2">
          <%= cl_image_tag trainer.photo.key, width: 150, height: 300, crop: :fill %>
        </div>
        <div class="infos">
            <div class="custom-color fs-3"> <%= trainer.name %></div>
            <div class="fs-4"><%= trainer.age %> years old</div>
        </div>
      </div>
    <% end %>
    <% end %>
  </div>
        <%= link_to "New Trainer", new_trainer_path, class: "btn btn-primary fw-bold my-5" %>

app/views/trainers/new.html.erb
<div class="mt-3">
  <%= link_to "< All Trainers", trainers_path, class:"custom-color fs-3" %>
</div>

  <div class="new-trainer mt-3">
    <div class="title-new fs-2">
      Sign up to train
    </div>

  <div class="form-new-trainer my-3">
    <%= simple_form_for (@trainer) do |f| %>
    <%= f.label :name, class:"text-white mt-3" %>
    <%= f.text_field :name , input_html: { class: "form-control text-dark bg-light pe-3" }  %>
    <%= f.label :age, class: "text-white ps-3 pb-3" %>
    <%= f.text_field :age, input_html: { class: "form-control text-dark bg-light pb-3" }  %>
    <%= f.input :photo, as: :file %>
    <%= f.submit %>
    <% end %>
  </div>

</div>

app/views/trainers/show.html.erb
<%= link_to "< Trainers", trainers_path, class:"custom-color fs-3" %>
<div class="title mt-3"><%= @trainer.name%> is going to catch 'em all !</div>

<div class="text-center fs-2">Their Pokemon </div>
<div class="trainer-container">
  <div class="trainer-card my-3 p-5">
    <div class="trainer-show">
      <div class="img pb-2">
        <%= cl_image_tag @trainer.photo.key, height: 300, width:250 %>
      </div>
      <div class="infos">
        <div class="fs-2"> <%= @trainer.name %></div>
        <div class="fs-3"><%= @trainer.age %> years old</div>
      </div>
      </div>
  </div>


    <div class="pokemon-catched" >
        <% @pokeballs.each do |pokeball| %>
          <div class="pokeball-card px-3">
            <%= cl_image_tag pokeball.pokemon.photo.key, width: 150, height: 280, crop: :fill %>
              <p class= "fs-2"><%= pokeball.pokemon.name %></p>
              <p class="text-dark fs-3">caught on <%= pokeball.caught_on %>
              at <%= pokeball.location  %></p>
              <%= link_to "Release", pokeball_path(pokeball),
                  data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
                   class:"btn btn-danger mb-3" %>
                   <%= link_to "", pokemon_path(pokeball.pokemon), class: "pokemon-card-link" %>
          </div>
        <% end %>
    </div>

</div>